import Hairline from '@/components/ui/Hairline';

const PRODUCT_LINKS = [
  { label: 'Product', href: '#hero' },
  { label: 'Pricing', href: '#pricing' },
  { label: 'Changelog', href: '/changelog' },
  { label: 'Status', href: '#' },
  { label: 'Privacy', href: '/privacy' },
];

const SOCIAL_LINKS = [
  { label: 'Twitter/X', href: '#' },
  { label: 'GitHub', href: '#' },
  { label: 'Email', href: 'mailto:hello@goon.so' },
];

export default function Footer() {
  return (
    <footer className="pb-8">
      <Hairline />
      <div className="max-w-6xl mx-auto px-4 md:px-6 pt-12">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-10 md:gap-8 mb-12">
          {/* Col 1: Wordmark */}
          <div>
            <span className="font-display font-semibold text-20 text-gradient-static">
              Goon
            </span>
            <p className="text-14 text-text-mid mt-3 leading-relaxed">
              Made by humans, generated by Goon.
            </p>
          </div>

          {/* Col 2: Product links */}
          <div>
            <h4 className="font-mono text-11 uppercase tracking-wider text-text-lo mb-4">
              Product
            </h4>
            <ul className="space-y-2">
              {PRODUCT_LINKS.map((link) => (
                <li key={link.label}>
                  <a
                    href={link.href}
                    className="text-14 text-text-mid hover:text-text-hi transition-colors"
                  >
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* Col 3: Social links */}
          <div>
            <h4 className="font-mono text-11 uppercase tracking-wider text-text-lo mb-4">
              Connect
            </h4>
            <ul className="space-y-2">
              {SOCIAL_LINKS.map((link) => (
                <li key={link.label}>
                  <a
                    href={link.href}
                    className="text-14 text-text-mid hover:text-text-hi transition-colors"
                  >
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <Hairline />

        <div className="pt-6 font-mono text-12 text-text-lo text-center md:text-left">
          © 2025 Goon · v0.1.4 · built in [city redacted]
        </div>
      </div>
    </footer>
  );
}
